package Chapter3;
public class Last4Panels extends javax.swing.JPanel {

    public Last4Panels() {
        initComponents();
        jTextArea1.setEditable(false);
        jTextArea2.setEditable(false);
        jTextArea3.setEditable(false);
        jTextArea4.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NET PLOT AREA AND COMPUTATION OF FSI");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("i) In case of a plotted layout / sub-division / group housing scheme / any development, net area shall be the balance  \nplot area after  deducting the area covered by amenity space under Regulation No.3.5 and Development / Regional Plan \nproposals including new roads and road widening, if any, from the total area of plot. \nii) For the purpose of computation of FSI / built-up area, the net area of the plot shall only be considered.  \niii) In case of plotted layout, the basic FSI of such net area shall be distributed on all plots on pro-rata basis or on certain\nplots as land owner desires, subject to maximum receiving potential prescribed in these regulations. \nHowever, such entitlement of FSI on certain plots shall be clearly mentioned on the layout plan.  \niv) In case of plots from already approved layouts, the plot area shall be treated as net plot area. \nv) The above regulations in respect of net plot area and computation of FSI shall apply to proposals in all land use zones.");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TRANSFER OF LAND UNDER D.P. SITES (OTHER THAN D.P. ROAD) IN LIEU OF FSI ");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("i) If an owner hands over a reserved site to the Authority free of cost, they can use its FSI on the remaining land, equivalent \nto TDR.\nii) A transfer deed must be executed, and FSI details included in the development proposal.\niii) In plotted layouts, FSI can be distributed as per owner’s choice, within the maximum permissible limit based on road \nwidth (Regulation 6.3).\niv) The receiving plot must have a minimum 9m road frontage.\nv) Unused FSI can be claimed as TDR.\nvi) If FSI is utilized on-site, DRC procedure is not required.");
        jScrollPane3.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("RELOCATION OF D.P. / R.P. SITES / ROADS");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("A) Shifting of reservations is allowed without altering the reserved area but not permitted if:\n\ti) It is split into multiple parts.\n\tii) It moves beyond 500m from its original location.\n\tiii) It moves outside the owner’s holding.\n\tiv) The new location differs significantly in access, levels, or size.\n\tv) It has already been relocated under these regulations.\n\tvi) It involves geo-sensitive land (e.g., biodiversity zones, nallahs).\n\tvii) It is outside the sanctioned layout area.\n\nB) Approval Process:\n\ti) Authority handles the relocation and reports it to the Government & Town Planning Director.\n\tii) The Development Plan is deemed modified upon approval.\n\nC) Relocation to Another Owner’s Land:\n\ti) Allowed within 300m if the other owner consents via a registered deed and hands over land in \n\texchange for TDR.\n\tii) Restrictions of sub-regulations (d), (e), and (f) apply.\n\tiii) No layout submission is required from the consenting owner.\n\nD) Road Alignment Shifts:\n\ti) Allowed if inlet & outlet points remain unchanged and traffic flow is unaffected.\n\tii) Must be approved by the Divisional Joint Director of Town Planning for smaller municipalities and \n\tregional areas.\n\tiii) The Development/Regional Plan is deemed modified accordingly.");
        jScrollPane4.setViewportView(jTextArea3);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("AMALGAMATION OF PLOTS");

        jScrollPane5.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("i) Amalgamation of plots / lands shall be permissible if they form a sizable plot from planning point of \nview and are contiguous. \nii) Amenity and layout plot shall also be entitled for amalgamation provided amenity is developed on proportionate area.\niii) Land separated by minor water course or nallah or road may be entitled for amalgamation provided connecting \nover bridge or under pass of sufficient width and strength is constructed by the owner with the approval of the Authority.");
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel3))
                                .addComponent(jScrollPane3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addComponent(jLabel4))
                                .addComponent(jScrollPane4))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
