package Chapter3;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Roads_StreetsinLandSubDivison extends javax.swing.JPanel {

    /**
     * Creates new form Roads_StreetsinLandSubDivison
     */
    public Roads_StreetsinLandSubDivison() {
        initComponents();
         ButtonGroup bg1= new ButtonGroup();
        bg1.add(jRadioButton1);
        bg1.add(jRadioButton2);
        bg1.add(jRadioButton5);
        bg1.add(jRadioButton6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jRadioButton6 = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Roads/Streets in Land Sub-Divisions or Layout");

        jRadioButton1.setText("For Residential Development");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("For Other Than Residential Development");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Group Housing Scheme");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Min. Length of Internal Road", "Min. Width of Internal Road"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jRadioButton6.setText("Pathways");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton2)))
                    .addComponent(jLabel5))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 33, 6);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        DefaultTableModel m1=(DefaultTableModel)jTable2.getModel();
        m1.setRowCount(0);
        m1.setColumnIdentifiers(new Object[]{"Min. Length of Internal Road", "Min. Width of the Internal Road"});
        m1.addRow(new Object[]{"Upto 150 m.","9.0 m."});
        m1.addRow(new Object[]{"Above 150 m. to 300 m.","12.0 m."});
        m1.addRow(new Object[]{"Above 300 m.","15.0 m."});
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        DefaultTableModel m1=(DefaultTableModel)jTable2.getModel();
        m1.setRowCount(0);
        m1.setColumnIdentifiers(new Object[]{"Min. Length of Internal Road", "Min. Width of the Internal Road"});
        m1.addRow(new Object[]{"Upto 150 m.","12.0 m."});
        m1.addRow(new Object[]{"Above 150 m. to 300 m.","15.0 m."});
        m1.addRow(new Object[]{"Above 300 m.","18.0 m. or more"});
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        DefaultTableModel m1=(DefaultTableModel)jTable2.getModel();
        m1.setRowCount(0);
        m1.setColumnIdentifiers(new Object[]{"Min. Length of Internal Road", "Min. Width of the Internal Road"});
        m1.addRow(new Object[]{"Upto 150 m.","7.5 m."});
        m1.addRow(new Object[]{"Above 150 m. to 300 m.","9.0 m."});
        m1.addRow(new Object[]{"Above 300 m. to upto 600","12.0 m."});
        m1.addRow(new Object[]{"Above 600 m.","15.0 m."});
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        DefaultTableModel m1 = (DefaultTableModel) jTable2.getModel();
        m1.setRowCount(0);
        m1.setColumnIdentifiers(new Object[]{"Length of Exit Ways", "Min. Width of the Paved Pathway"});
        m1.addRow(new Object[]{"upto 40 m.","2.0 m."});
        m1.addRow(new Object[]{"upto 60 m. to 300 m.","3.0 m."});
        m1.addRow(new Object[]{"upto 100 m.","4.5 m."});
        m1.addRow(new Object[]{"Above 100 m.","7.5 m."});
        m1.addRow(new Object[]{"Above 150 m. to 300 m.","9.0 m."});
        m1.addRow(new Object[]{"Above 300 m. to upto 600","12.0 m."});
        m1.addRow(new Object[]{"Above 600 m.","15.0 m."});
    }//GEN-LAST:event_jRadioButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
